# Generated by Django 3.0.4 on 2020-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200320_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='context',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
