# Generated by Django 3.0.4 on 2020-03-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200322_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='LectureNote',
        ),
    ]
