# Generated by Django 3.0.4 on 2020-03-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20200322_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturenote',
            name='context',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lecturenote',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.LectureNote')),
            ],
        ),
    ]
