# Generated by Django 3.0.4 on 2020-04-11 11:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20200331_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturenote',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
