# Generated by Django 3.0.4 on 2020-06-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20200610_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturenote',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
